- hosts: all
  gather_facts: no
  tasks:
    - name: Install requirements
      block:
        - name: Install Docker and pip
          package:
            name: '{{ item }}'
            state: present
          loop:
            - docker
            - python-pip

        # Using pip in order to have the latest version
        - name: Install docker-compose
          pip:
            name: docker-compose

        - name: Start the docker service
          systemd:
            name: docker
            state: started

    - name: Clone the example Rails app
      git:
        repo: https://github.com/honestica/docker-compose-rails-dev-example
        dest: '{{ app_dir }}'
        version: master

    - name: Configure secrets
      blockinfile:
        path: '{{ app_dir }}/config/secrets.yml'
        create: yes
        block: |
          development:
            secret_token: '{{ secret_token }}'
            secret_key_base: '{{ secret_key_base }}'

    - name: Configure .env file
      lineinfile:
        path: '{{ app_dir }}/.env'
        create: yes
        regexp: '^SECRET_KEY_BASE='
        line: SECRET_KEY_BASE={{ secret_key_base }}

    # On first run, we need to run only the 'web' and 'jobs' services
    # in order to populate the keyring with necessary PGP keys
    - name: Launch app (only 'web' and 'jobs' services if fail)
      block:
        - name: Launch app
          docker_service:
            project_src: '{{ app_dir }}'

      rescue:
        - name: Launch only 'web' and 'jobs' services
          docker_service:
            project_src: '{{ app_dir }}'
            services:
              - web
              - jobs

        - name: Stop the containers
          docker_service:
            project_src: '{{ app_dir }}'
            state: absent

        - name: Launch it all again
          docker_service:
            project_src: '{{ app_dir }}'
